### ISSUE TITLE
Link documentEditViewController to the document list

### ISSUE THREAD

**Issue by darren2pro** [Annotato/annotato#12]
Implementing this will allow us to instantiate the document edit view controller by clicking one of the document icons in the document list view

I have already written the method that will take in a documentpdfviewmodel and display the view based on that model already, just need to link it up

**Comment by zognin** [comment]
@darren2pro To do this, `DocumentListViewModel` needs an `id`. Using the id, you fetch the `DocumentViewModel`. Refer to comment in `didSelectCellView` method in https://github.com/Annotato/annotato/blob/384cc837746698a948b05fc0eb12ac9fcaedf21e/Annotato/Annotato/Views/Document/List/DocumentListViewController.swift

You cannot just get a `DocumentViewModel` from the `DocumentPdfViewModel`. How will the pdf view model know about the other attributes of its existing parent `DocumentViewModel`??

**Comment by sivayogasubramanian** [comment]
Done in https://github.com/Annotato/annotato/pull/41
