### ISSUE TITLE
Min/Max not working for annotations

### ISSUE THREAD

**Issue by sivayogasubramanian** [Annotato/annotato#47]
<img width="313" alt="Screenshot 2022-03-19 at 9 11 23 PM" src="https://user-images.githubusercontent.com/53614454/159122443-236cefb3-4d42-4ddc-ae3c-a2c0e9fb6b2c.png">

<img width="306" alt="Screenshot 2022-03-19 at 9 13 12 PM" src="https://user-images.githubusercontent.com/53614454/159122517-71e352fa-c207-4903-90ce-84d24544f39f.png">

Clicking the button does not do anything to the annotation's height.

**Comment by darren2pro** [comment]
I remember it worked in the past

If it's because of some integration issues when resolving merge conflicts then my bad about that guys

**Comment by zognin** [comment]
This is intentional. The minimize function minimizes to the first section. If you don't want this then we can make it minimized to a constant height.

**Comment by zognin** [comment]
Fixed in #62
